### ISSUE TITLE
missing argument label in call (have actions, expected options)

### ISSUE THREAD

**Issue by elsifi** [SwiftKitz/Appz#100]
![screen shot 2017-06-09 at 12 49 50 pm](https://user-images.githubusercontent.com/1190843/26972457-30bf9ad2-4d12-11e7-8812-30c0d4e12db0.jpg)

installed via cocoaPods
project is Swift 3

**Comment by Mazyod** [comment]
Thanks, README is now updated.

**Background**: 
README had some outdated code using `.Status` enum with capital letter, which causes an error since enums where changed to small letters in Swift 3.

Please use `.status` instead.

**Comment by elsifi** [comment]
Thanks (Y)
