### ISSUE TITLE
A suggestion: supported platform versions

### ISSUE THREAD

**Issue by Maryom** [SwiftKitz/Appz#107]
Hey,

I found this 👇🏼

<img width="388" alt="screen shot 2017-09-26 at 3 40 19 pm" src="https://user-images.githubusercontent.com/3218401/30860811-23158166-a2d1-11e7-8650-561bc8d4620e.png">

I would I like to add it to all SwiftKitz repos. It's fine ?

Can you please provide me with all the supported platform versions ? or could you please guide me to an easy way to find the supported platform versions ?

Thanks.

**Comment by Mazyod** [comment]
Thanks, but I think it's not worth adding and maintaining for now.

**Comment by Maryom** [comment]
As you like.

**Comment by Maryom** [comment]
Please when it's the time please tell me to do it, I will be glad to help.
Thanks.

**Comment by Maryom** [comment]
I found a way to find the supported platform versions, For example: Appz, supported platform versions are as follow: 

- iOS 8.0+
- tvOS 9.0+
- watchOS 2.0+

TYT, when it's the time give me the agreement to do them to all SwiftKitz repos.
