### ISSUE TITLE
Google Drive opens Safari only

### ISSUE THREAD

**Issue by OndrejHRIC** [SwiftKitz/Appz#125]
I'm calling this and it gets me to Safari tab, instead of app, that's installed a it was opened before.

`UIApplication.shared.open(Applications.GoogleDrive(), action: .open)`

This code gets me to the Google Maps app.

`UIApplication.shared.open(Applications.GoogleMaps(), action: .open)`

**Comment by Mazyod** [comment]
Hello, are you sure you have added `googlemaps` to the known schemes in info.plist?

**Comment by OndrejHRIC** [comment]
Yeah, sorry, I missed it.
Thanks👍
