### ISSUE TITLE
URL scheme for Google Calendar

### ISSUE THREAD

**Issue by vin-zhou** [SwiftKitz/Appz#138]
Hi @Dreamersoul,
  thanks for this great project!
  I want to ask,  is there a way to pass the event detail info to Google Calendar by the scheme?  I've searched for a long time but no useful result was found. (Google Maps provide one : https://developers.google.com/maps/documentation/urls/ios-urlscheme , but not good for the calendar). 
 I try my luck here, any advise will be appreciated.
 Thanks again.

**Comment by Dreamersoul** [comment]
Greetings! This project is mainly an effort by @mazyod he deserves all the credit! 
The thing is we had a hard time finding iOS schemes! If you find that we are missing any please let us know! Thank you

**Comment by Maryom** [comment]
Hey,

We took Google Calendar scheme from [here](https://forums.macrumors.com/threads/ios-8-widget-customisations-using-launcher.1782093/) 

@vin-zhou I hope this will help.
