### ISSUE TITLE
About versioning

### ISSUE THREAD

**Issue by Dreamersoul** [SwiftKitz/Appz#21]
I have noticed that the version of this library is still at v1.0.0, Should we increment it in the readme file and the podespec or what?

**Comment by Mazyod** [comment]
yeah, good point. The checklist is:
- [ ] update the change log
- [ ] draft a new release on github
- [ ] update readme (where ever it says vx.x.x)
- [ ] increment the version in the podspec
- [ ] create a new tag on that new commit (e.g. v1.1.0)
- [ ] push the new spec to the cocoapods spec repo (I think only I can do that)
