### ISSUE TITLE
Allow opening the AppStore to download a missing app

### ISSUE THREAD

**Issue by Mazyod** [SwiftKitz/Appz#32]
It would be great to add a capability for developers to redirect users to the AppStore in order to download a specific app, in case it is missing. This feature doesn't work for all applications, since some applications have web interfaces we can use instead, without downloading the app.

The feature should be designed such that the developer would willingly opt-in to opening the AppStore for downloading the specific app if it is missing, and doesn't just happen transparently.

**Comment by Maryom** [comment]
Nice idea :) I'm so excited to implement it but I was thinking to add these apps to Appz:
http://forums.macrumors.com/threads/ios-8-widget-customisations-using-launcher.1782093/

Do you think it's better to start adding these apps then try to implement the enhancement?

**Comment by Mazyod** [comment]
This issue is assigned to milestone `v2.0.0`, so it will be a while before it makes it .. We can proceed with other enhancements for the time being.
