### ISSUE TITLE
LSApplicationQueriesSchemes in plist

### ISSUE THREAD

**Issue by Dreamersoul** [SwiftKitz/Appz#56]
i was testing the library on a dummy app im working on, and found that i need to add the apps uri scheme in the info.plist file in iOS 9 primarily
is there is a way to avoid that or even add our own plist file in the library with all the shemes so that developers using this library use it as a reference?

**Comment by Mazyod** [comment]
The schemes are already there in the application definitions, and adding the custom URL schemes is described in the readme guide.

I really don't think we can do anything about that.
