### ISSUE TITLE
Update docs and playground

### ISSUE THREAD

**Issue by Mazyod** [SwiftKitz/Appz#7]
Thanks to #6, we have mail and SMS support. We should update the readme and playground with those.

**Comment by h0lyalg0rithm** [comment]
I think we should start moving them to seperate wiki pages and just refer them in the readme

**Comment by Mazyod** [comment]
@h0lyalg0rithm I thought about that, and realized we want a compact set of features per library such that the doc should fit one page. So, it's as if each kit's readme is a wiki page, sort to speak.

I do see where you are coming from, though. Huge projects like Cocos2d or similar should probably always keep their README minimal, and direct to a structured docs site.
