### ISSUE TITLE
Two apps not installed with pod install

### ISSUE THREAD

**Issue by Maryom** [SwiftKitz/Appz#83]
Salaam,

I discovered a weird issue! when I run pod install everything installed except the two apps, I added yesterday. I'm sure I added them to all targets: iOS, tvos, and watchOS. And the most weird part is when I downloaded Appz as zip file I found these two apps: NYTimes, and Skitch. Any suggestion?

<img width="559" alt="screen shot 2016-09-21 at 10 31 35 pm" src="https://cloud.githubusercontent.com/assets/3218401/18726164/d5f99f14-804b-11e6-8b72-45059e75d44e.png">

**Comment by Mazyod** [comment]
I released a new version to Cocoapods (v2.0.1) that contains the apps. Please try running:

``` sh
$ pod update Appz
```

**Comment by Maryom** [comment]
Ok Thanks for updating it. If you don't mind me asking: why it didn't install the apps with version 2.0.0 and why it installed them with v 2.0.1 ? maybe it's a stupid question but I want to learn.

**Comment by Mazyod** [comment]
Of course it's not a stupid question, I just thought you already know.

Take a look here:
https://github.com/SwiftKitz/Appz/releases

You can see the library versions that have been released in the past. Once a new version is released, a git "tag" is added to a specific commit. So, for example, if someone downloads v2.0.0 100 years from now, it will still be the same code. Everytime we change the library by adding more commits, then we can make a new release by creating a new tag.

For example, this is v2.0.0 .. the two apps are not there:
https://github.com/SwiftKitz/Appz/tree/v2.0.0

This is v2.0.1, where you can find the apps:
https://github.com/SwiftKitz/Appz/tree/v2.0.1

this is the oldest version, it never changes:
https://github.com/SwiftKitz/Appz/tree/v1.0.0

**Comment by Maryom** [comment]
Thanks @Mazyod :) Can I ask one more question:
The two apps were merged in PR #81, while v2.0.0 just has PR #76 as a new one. That's why the two apps didn't appear in v2.0.0 ?

**Comment by Mazyod** [comment]
Exactly. I made v2.0.0 release before merging your PR

**Comment by Maryom** [comment]
Thank you so much for the explanation and for learning me a new stuff: awesome stuff 👍🏼
