### ISSUE TITLE
Just the needed app

### ISSUE THREAD

**Issue by Maryom** [SwiftKitz/Appz#85]
Salaam,

I'm thinking of a way to give the developer the ability to just install the app he/she need. Because maybe the developer just need one or few apps so no need to install 155 apps, Do you agree with me?

I think we can offer this feature but I don't know how but I'm thinking, searching, and sharing thoughts so we will solve it إن شاء الله

Hmm, I think the best way is to combine all apps with just open action together (one class), and then use enum or .. to decide which scheme, baseURL, and paths to use. Do you agree? this will reduce file number to more than half.

Maybe my thinking is wrong but I think we have to reduce file number ..

**Comment by Mazyod** [comment]
Putting all apps into a single file won't allow us to implement a way to allow users to specify which app they are interested in. It will also cause a very large enum, which is not useful in this case.
