### ISSUE TITLE
Trigger opening in Docs@Work

### ISSUE THREAD

**Issue by bratislav** [SwiftKitz/Appz#93]
Hello,

Not sure how exactly this library works (not an iOS developer), but is it possible to trigger opening of an arbitrary document like docx/xlsx/pdf (from an URL location) inside an external office app e.g. MobileIron's Docs@Work? Is it enough to write another swift file and somehow embed this into my own app?

My app deals with documents and the security is handled by MobileIron. MobileIron is a type of EMM and what they do is they wrap IPA files into a secure containers and, on the other side, also provide a sort of Office app called Docs@Work which is used to open all these formats in read-only mode (no copy-paste, sharing etc).

Can I trigger document opening from my app using your Appz library?

Many thanks,
Baki

**Comment by Mazyod** [comment]
Thanks for asking, Baki.

You can think of Appz as: "a simple collection of specs that define the parameters iOS app use for deeplinking". As long as you can find out what the specs are for MobileIron's deeplinking, you can simply fork this repo, create a new file similar to the other specs, and write those specs there. Then, you can use your fork in your own apps.

If you submit a PR to us, it will be greatly appreciated, and we will merge it so you, and everyone else, can use it.

**Comment by Mazyod** [comment]
Please don't hesitate to ask or reopen if you need anything else.
