### ISSUE TITLE
FourSquare error 

### ISSUE THREAD

**Issue by alexanderkhitev** [SwiftKitz/Appz#97]
Hello! Thanks for the framework. I use it to open the FourSquare app, but I get the error -canOpenURL: failed for URL: "foursquare:" - error: "I could add foursquare to Info. Plist. Please tell me how can I fix this?

**Comment by Mazyod** [comment]
Hey! Thanks for using this library.
Please see the readme section regarding adding ULR schemes to the info plist. That's should resolve your issue. Please reopen if that doesn't solve your issue!

**Comment by alexanderkhitev** [comment]
@Mazyod  Thank you very much for the quick response. Yes, added a foursquare key to info.plist. I added it before, but the problem is not solved.
	
```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>foursquare</string>
		<string>comgooglemaps</string>
		<string>googlechromes</string>
		<string>fbapi</string>
		<string>fb-messenger-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
		<string>foursquareauth</string>
	</array>
```

**Comment by Mazyod** [comment]
Are you testing on a real device with four square installed?

**Comment by alexanderkhitev** [comment]
@Mazyod Yes, I tested on real iPhone 7.
Updated: I also rebooted the device

**Comment by Mazyod** [comment]
I'll look into it

**Comment by alexanderkhitev** [comment]
@Mazyod Now I will try to delete the cache with xcode to reinstall foursquare and write to you.

**Comment by Mazyod** [comment]
Honestly, I'm betting the issue might either be in your plist structure or our definition of the foursquare deeplinks

**Comment by alexanderkhitev** [comment]
@Mazyod  After reinstalling the foursquare and removing the xcode cache, it all worked out, I'm sorry that took up your time.

**Comment by Mazyod** [comment]
Thanks for sharing your experience!! I'm sure it will help others here in the future, myself included!
