### ISSUE TITLE
Update the pod version 

### ISSUE THREAD

**Issue by floriangbh** [SwiftKitz/Appz#99]
Could be cool to update the pod version with le latest PRs and updates :) 

Thank you for this library 👍

**Comment by Mazyod** [comment]
Your wish is our commit :)

**Comment by terflogag** [comment]
Ohhh thank you 👍

**Comment by floriangbh** [comment]
Got the old version 2.0.1, maybe forgot to trunk push ? :)

**Comment by Mazyod** [comment]
Nah, I pushed to trunk. It should be available now or soonish.

**Comment by floriangbh** [comment]
now it's ok, thank you :)
